title: احسان رفیعی نژاد
email: ehsan.rafieinezhad@gmail.com
baseurl: ''
url: 'http://ehsanrafieinezhad.github.io'
author: احسان رفیعی نژاد

plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jemoji
  - jekyll-seo-tag

permalink: /:categories/:year/:month/:day/:title/

defaults:
  - values:
      lang: 'fa_IR'
  - scope:
      path: ''
      type: 'posts'
    values:
      layout: 'post'
  - scope:
      path: ''
      type: 'pages'
    values:
      layout: 'page'

feed:
  path: /feed.xml
